spring:
  datasource:
    url: jdbc:mysql://localhost:3306/geyule
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    #type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml